use crate::elements::tokens::Tokens;

pub const HEADING_ONE: Tokens = Tokens::HeadingOne("# ");
pub const HEADING_TWO: Tokens = Tokens::HeadingTwo("## ");
pub const HEADING_THREE: Tokens = Tokens::HeadingThree("### ");
pub const HEADING_FOUR: Tokens = Tokens::HeadingFour("#### ");
pub const HEADING_FIVE: Tokens = Tokens::HeadingFive("##### ");
pub const HEADING_SIX: Tokens = Tokens::HeadingSix("###### ");
pub const ORDERED_LIST_NUMBER: Tokens = Tokens::OrderedListNumber(r"^\d+\.\s");
pub const UNORDERED_LIST_HYPHEN: Tokens = Tokens::UnorderedListHyphen("- ");
pub const TASK_LIST: Tokens = Tokens::TaskList("- [ ] ");
pub const DEFINITION_LIST: Tokens = Tokens::DefinitionList(": ");
pub const BLOCKQUOTE: Tokens = Tokens::Blockquote("> ");
pub const MARKDOWN_BLOCK: Tokens = Tokens::MarkdownBlock("```md");
pub const C_BLOCK: Tokens = Tokens::CBlock("```c");
pub const CODE_BLOCK: Tokens = Tokens::CodeBlock("```");
pub const HORIZONTAL_RULE_HYPHEN: Tokens = Tokens::HorizontalRuleHyphen("---");
pub const HORIZONTAL_RULE_ASTERISK: Tokens = Tokens::HorizontalRuleAsterisk("***");
pub const HORIZONTAL_RULE_UNDERSCORE: Tokens = Tokens::HorizontalRuleUnderscore("___");
pub const EMPTY_LINE: Tokens = Tokens::EmptyLine("");
pub const LINE_BREAK: Tokens = Tokens::LineBreak("  ");
